'use strict';
const fs=require('fs');
const {TextEncoder}=require('util');
const te=new TextEncoder();
function book_new(){return{SheetNames:[],Sheets:{}}}
function aoa_to_sheet(rows){return{__rows:Array.isArray(rows)?rows:[]}}
function json_to_sheet(data){const rows=Array.isArray(data)?data:[];if(!rows.length)return aoa_to_sheet([]);const headers=[];for(const r of rows)for(const k of Object.keys(r||{}))if(!headers.includes(k))headers.push(k);return aoa_to_sheet([headers,...rows.map(r=>headers.map(h=>r?.[h]??''))])}
function book_append_sheet(wb,ws,name){let n=String(name||'Sheet').slice(0,31).replace(/[\\/?*\[\]:]/g,'_');if(!n)n='Sheet';let base=n,i=2;while(wb.Sheets[n])n=(base.slice(0,28)+'_'+i++).slice(0,31);wb.SheetNames.push(n);wb.Sheets[n]=ws}
function xesc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[m]))}
function colName(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s}
function sheetXml(ws){const rows=ws.__rows||[];const widths=(ws['!cols']||[]).map((x,i)=>x?.wch?`<col min="${i+1}" max="${i+1}" width="${Number(x.wch)}" customWidth="1"/>`:'').join('');let out='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'+(widths?`<cols>${widths}</cols>`:'')+'<sheetData>';rows.forEach((row,ri)=>{out+=`<row r="${ri+1}">`;for(let ci=0;ci<row.length;ci++){const v=row[ci],ref=colName(ci)+(ri+1);if(typeof v==='number'&&Number.isFinite(v))out+=`<c r="${ref}"><v>${v}</v></c>`;else if(typeof v==='boolean')out+=`<c r="${ref}" t="b"><v>${v?1:0}</v></c>`;else out+=`<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${xesc(v)}</t></is></c>`;}out+='</row>'});return out+'</sheetData></worksheet>'}
function u16(n){const b=Buffer.alloc(2);b.writeUInt16LE(n>>>0);return b}function u32(n){const b=Buffer.alloc(4);b.writeUInt32LE(n>>>0);return b}
let crcTable=null;function crc32(buf){if(!crcTable){crcTable=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;crcTable[n]=c>>>0}}let c=0xffffffff;for(const x of buf)c=crcTable[(c^x)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function zip(entries){const locals=[],centrals=[];let offset=0;for(const [name,text] of entries){const nb=Buffer.from(name),db=Buffer.from(text),crc=crc32(db);const local=Buffer.concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(db.length),u32(db.length),u16(nb.length),u16(0),nb,db]);locals.push(local);const central=Buffer.concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(db.length),u32(db.length),u16(nb.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),nb]);centrals.push(central);offset+=local.length}const body=Buffer.concat(locals),cd=Buffer.concat(centrals),end=Buffer.concat([u32(0x06054b50),u16(0),u16(0),u16(entries.length),u16(entries.length),u32(cd.length),u32(body.length),u16(0)]);return Buffer.concat([body,cd,end])}
function writeFile(wb,file){const sheets=wb.SheetNames.map(n=>[n,wb.Sheets[n]]);const types='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'+sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')+'</Types>';
const rels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>';
const workbook='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'+sheets.map((s,i)=>`<sheet name="${xesc(s[0])}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')+'</sheets></workbook>';
const wbRels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')+`<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;
const styles='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="1"><font><sz val="11"/><name val="Calibri"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="1"><xf xfId="0"/></cellXfs></styleSheet>';
const entries=[['[Content_Types].xml',types],['_rels/.rels',rels],['xl/workbook.xml',workbook],['xl/_rels/workbook.xml.rels',wbRels],['xl/styles.xml',styles],...sheets.map((s,i)=>[`xl/worksheets/sheet${i+1}.xml`,sheetXml(s[1])])];fs.writeFileSync(file,zip(entries));}
module.exports={utils:{book_new,aoa_to_sheet,json_to_sheet,book_append_sheet},writeFile};
